{"uuid":"0f650908-0e1d-4fbf-94c7-c1dc89367877","historyId":"5affa0a7f0f41c28e1b0610d41f17201","fullName":"org.example.AppTest.testValidLogin","labels":[{"name":"package","value":"org.example.AppTest"},{"name":"testClass","value":"org.example.AppTest"},{"name":"testMethod","value":"testValidLogin"},{"name":"parentSuite","value":"Example Test Suite"},{"name":"suite","value":"AppTest Execution"},{"name":"subSuite","value":"org.example.AppTest"},{"name":"host","value":"CKMAC187.local"},{"name":"thread","value":"56617@CKMAC187.local.TestNG-test=AppTest Execution-2(16)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"feature","value":"Login with valid credentials"},{"name":"epic","value":"User Authentication"}],"links":[],"name":"testValidLogin","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"java.io.IOException: Output closed\nBuild info: version: '4.26.0', revision: '8ccf0219d7'\nSystem info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.2.1', java.version: '17.0.12'\nDriver info: driver.version: ChromiumDriver","trace":"org.openqa.selenium.WebDriverException: java.io.IOException: Output closed\nBuild info: version: '4.26.0', revision: '8ccf0219d7'\nSystem info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.2.1', java.version: '17.0.12'\nDriver info: driver.version: ChromiumDriver\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient$4.send(JdkHttpClient.java:321)\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient$4.close(JdkHttpClient.java:340)\n\tat org.openqa.selenium.devtools.Connection.close(Connection.java:226)\n\tat org.openqa.selenium.devtools.DevTools.close(DevTools.java:61)\n\tat java.base/java.util.Optional.ifPresent(Optional.java:178)\n\tat org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:439)\n\tat org.openqa.selenium.chromium.ChromiumDriver.quit(ChromiumDriver.java:436)\n\tat org.example.framework.TestAutomationFramework.closeBrowser(TestAutomationFramework.java:32)\n\tat org.example.AppTest.tearDown(AppTest.java:42)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)\n\tat org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)\n\tat org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:646)\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:842)\nCaused by: java.io.IOException: Output closed\n\tat java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.sendClose(WebSocketImpl.java:313)\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient$4.lambda$send$2(JdkHttpClient.java:286)\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient$4.send(JdkHttpClient.java:311)\n\t... 24 more\n"},"stage":"finished","description":"This test verifies that a user can log in with valid credentials.","steps":[],"attachments":[],"parameters":[],"start":1732091950796,"stop":1732091950796}