{"uuid":"f9e0b4ad-6eab-4e24-94a3-80b7a2c81a59","historyId":"a4571167f4ea2a4231003bee12e5c3d8","fullName":"org.example.AppTest.testInvalidLogin","labels":[{"name":"package","value":"org.example.AppTest"},{"name":"testClass","value":"org.example.AppTest"},{"name":"testMethod","value":"testInvalidLogin"},{"name":"parentSuite","value":"Example Test Suite"},{"name":"suite","value":"AppTest Execution"},{"name":"subSuite","value":"org.example.AppTest"},{"name":"host","value":"CKMAC187.local"},{"name":"thread","value":"60553@CKMAC187.local.TestNG-test=AppTest Execution-2(16)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"feature","value":"Login with invalid credentials"},{"name":"epic","value":"User Authentication"}],"links":[],"name":"testInvalidLogin","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Error message should be displayed. expected [true] but found [false]","trace":"java.lang.AssertionError: Error message should be displayed. expected [true] but found [false]\n\tat org.testng.Assert.fail(Assert.java:96)\n\tat org.testng.Assert.failNotEquals(Assert.java:776)\n\tat org.testng.Assert.assertTrue(Assert.java:44)\n\tat org.example.AppTest.verifyLoginError(AppTest.java:100)\n\tat org.example.AppTest.testInvalidLogin(AppTest.java:62)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:583)\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:842)\n"},"stage":"finished","description":"This test verifies that a user cannot log in with invalid credentials.","steps":[],"attachments":[],"parameters":[],"start":1732099120602,"stop":1732099152685}